use_frameworks!

platform :ios, '8.0'

target 'HYAnimationSmallTool_Example' do
  pod 'HYAnimationSmallTool', :path => '../'

  target 'HYAnimationSmallTool_Tests' do
    inherit! :search_paths

    
  end
end
